export type Fact = {id:string; label:string; tag:string; title:string; body:string; tip:string; sprite:number; color:string; source:string; sound:string};
const cp = 'https://www.cats.org.uk/';
export const facts:Fact[] = [
{id:'night',label:'ミラーボール',tag:'01 / ACTIVITY',title:'夜行性？ じつは、夕暮れ派。',body:'猫は、明け方と夕暮れに活発になりやすい「薄明薄暮性」の動物。獲物が動く時間に合わせた、ハンターの名残です。暮らす環境によって生活リズムは変わります。',tip:'夕方のひと遊び。猫のゴールデンタイムに付き合ってみよう。',sprite:1,color:'pink',source:cp+'help-and-advice/home-and-environment/cats-at-night',sound:'PARTY TIME!'},
{id:'ears',label:'DJねこ',tag:'02 / SENSES',title:'その耳、気持ちも聞かせてくれる。',body:'前を向く、横を向く、ぺたんと伏せる。猫の耳は音を探すだけでなく、気持ちを読み取る手がかりにも。耳だけで決めつけず、しっぽや姿勢も一緒に観察してみよう。',tip:'大きな音が苦手な子も。ほんものの猫には、静かな居場所を。',sprite:0,color:'lime',source:cp+'help-and-advice/cat-behaviour/cat-body-language',sound:'CHECK IT OUT!'},
{id:'hunt',label:'おどるねこ',tag:'03 / PLAY',title:'そのじゃれ方、小さなハンター。',body:'じっと狙って、追いかけて、飛びつく。おもちゃで遊ぶ動きには狩りの行動が詰まっています。お腹がいっぱいでも遊びたくなるのは、空腹だけが理由ではないから。',tip:'猫じゃらしは、時々ちゃんと捕まえさせて。達成感も大切。',sprite:1,color:'cyan',source:cp+'help-and-advice/cat-behaviour/cats-and-play',sound:'LET’S DANCE!'},
{id:'box',label:'はこねこ',tag:'04 / HIDEOUT',title:'その箱、最高のVIPルーム。',body:'体を隠せる場所は、猫にとって安心できる居場所。段ボール箱は、落ち着くためにも、遊びの待ち伏せにも使える、小さなひみつ基地なんです。',tip:'中にいるときは、無理に引っぱり出さず、そっと見守って。',sprite:2,color:'peach',source:cp+'help-and-advice/cat-behaviour/cats-hiding',sound:'DO NOT DISTURB'},
{id:'sleep',label:'おやすみねこ',tag:'05 / SLEEP',title:'寝るのも、ねこのお仕事。',body:'猫は1日におよそ12〜18時間眠ります。細切れに休みながら、遊びや探索に使うエネルギーを蓄えているんです。年齢や生活環境によっても眠る時間は変わります。',tip:'あたたかくて安全な寝床を。寝顔は起こさず楽しもう。',sprite:3,color:'lavender',source:cp+'help-and-advice/cat-behaviour/cats-and-sleep',sound:'ZZZ…'},
{id:'water',label:'ドリンクねこ',tag:'06 / WATER',title:'今夜の一杯は、お水です。',body:'猫には、いつでも飲める新鮮な水が必要です。ごはんとお水を離して置いたり、複数の場所に用意したりすると、好みの飲み場所を選べます。',tip:'このディスコのドリンクは空想の演出。猫のいつもの飲み物はお水。',sprite:4,color:'cyan',source:cp+'help-and-advice/diet/feeding',sound:'CHEERS, MEOW!'},
{id:'scratch',label:'つめとぎ',tag:'07 / SCRATCH',title:'バリバリは、ちゃんとした理由がある。',body:'爪とぎは、古い爪の外側をはがすお手入れ。体を伸ばしたり、においや跡で自分の場所を示したりする役割もあります。猫にとって自然な行動です。',tip:'縦が好き？ 横が好き？ その子に合う爪とぎを探そう。',sprite:5,color:'lime',source:cp+'help-and-advice/cat-behaviour/scratching',sound:'SCRATCH!'},
{id:'whisker',label:'ひげねこ',tag:'08 / WHISKERS',title:'ひげは、顔のまわりのセンサー。',body:'猫のひげは、触れたものや空気の動きを感じる大切な感覚器。近くのものを察知したり、暗がりを移動したりする助けになります。',tip:'ひげは飾りじゃありません。切らずに、そのままにしておこう。',sprite:4,color:'pink',source:cp+'cats-blog/why-do-cats-have-whiskers',sound:'I FEEL YOU'},
{id:'tail',label:'しっぽねこ',tag:'09 / BODY LANGUAGE',title:'しっぽは、ことばの代わり。',body:'ぴんと上がったしっぽは、友好的なあいさつの手がかり。強く振るしっぽは、いら立ちや緊張を表すことも。目や耳、体の姿勢と合わせて気持ちを読み取ろう。',tip:'しっぽを振る＝いつでもごきげん、ではないんです。',sprite:1,color:'peach',source:cp+'help-and-advice/cat-behaviour/cat-body-language',sound:'HELLO, HUMAN!'},
{id:'height',label:'キャットタワー',tag:'10 / SAFE PLACE',title:'高いところから、ひと休み。',body:'猫は、安心して休める居場所を大切にします。高い寝床なら周りを見渡しやすく、ひとりで落ち着くことも。好きな休み方は、猫それぞれです。',tip:'登る道と降りる道も、無理なく使えるように。',sprite:2,color:'lavender',source:cp+'help-and-advice/cat-behaviour/cats-and-sleep',sound:'MY VIP SEAT'},
{id:'toy',label:'猫じゃらし',tag:'11 / TOYS',title:'楽しさのコツは、ちょっとずつ。',body:'短い遊びを何度か楽しむのも、猫に合った遊び方。おもちゃを時々入れ替えると、新しいものへの好奇心もくすぐれます。',tip:'ひも付きのおもちゃは、遊び終わったら片づけよう。',sprite:0,color:'pink',source:cp+'help-and-advice/cat-behaviour/cats-and-play',sound:'ONE MORE PLAY!'},
{id:'hide',label:'かくれんぼ',tag:'12 / CAT PACE',title:'ひとりの時間も、だいじ。',body:'猫が隠れるのは、休んだり安心したりするための自然な行動でもあります。ずっとみんなと一緒でなくてもいい。近づくかどうかを自分で選べることも大切です。',tip:'遊ぶのも、休むのも、猫のペースで。',sprite:3,color:'lime',source:cp+'help-and-advice/cat-behaviour/cats-hiding',sound:'MY OWN PACE'},
];
